
export function img2imgReqBody(initImages: string, mask: string, prompt: string) {    
    return JSON.stringify({    "init_images": [initImages],
                "resize_mode": 0,
                "denoising_strength": 0.75,
                "mask": mask,
                "mask_blur": 4,
                "inpainting_fill": 1,
                "inpaint_full_res": "True",
                "inpaint_full_res_padding": 0,
                "inpainting_mask_invert": 0,
                "prompt": prompt,
                "styles": [],
                "seed": -1,
                "subseed": -1,
                "subseed_strength": 0,
                "seed_resize_from_h": -1,
                "seed_resize_from_w": -1,
                "batch_size": 1,
                "n_iter": 1,
                "steps": 40,
                "cfg_scale": 7,
                "width": 512,
                "height": 512,
                "restore_faces": "False",
                "tiling": "False",
                "negative_prompt": "",
                "eta": 0,
                "s_churn": 0,
                "s_tmax": 0,
                "s_tmin": 0,
                "s_noise": 1,
                "override_settings": {},
                "sampler_index": "Euler a",
                "include_init_images": "True"
    });
}